'use strict';

/* ===== Terrain (rendered once to an offscreen canvas) ===== */
let terrainCv = null;

/* ===== Unit sprites (generated by scripts/generate_sprites.js) ===== */
const SPRITE_CACHE = {};

function spriteSlug(name) {
  return name.toLowerCase().replace(/[^a-z]/g, '');
}

function preloadSprites() {
  for (const key of Object.keys(CARDS)) {
    const def = CARDS[key];
    if (def.spell || def.barrel) continue;
    const slug = spriteSlug(def.name);
    for (const team of [TEAM_BLUE, TEAM_RED, TEAM_GREEN]) {
      const img = new Image();
      img.src = `assets/sprites/${slug}_${team}.png`;
      SPRITE_CACHE[`${slug}_${team}`] = img;
    }
  }
}

function buildTerrain() {
  terrainCv = document.createElement('canvas');
  terrainCv.width = CANVAS_W;
  terrainCv.height = CANVAS_H;
  const c = terrainCv.getContext('2d');

  // Grass with alternating stripes
  c.fillStyle = '#3a7020';
  c.fillRect(0, 0, CANVAS_W, CANVAS_H);
  c.fillStyle = 'rgba(255,255,255,0.04)';
  for (let row = 0; row < ARENA_H; row += 2) c.fillRect(0, row * TILE, CANVAS_W, TILE);

  // Faint grid
  c.strokeStyle = 'rgba(0,0,0,0.06)';
  c.lineWidth = 1;
  for (let gx = 0; gx <= ARENA_W; gx++) {
    c.beginPath(); c.moveTo(gx * TILE, 0); c.lineTo(gx * TILE, CANVAS_H); c.stroke();
  }
  for (let gy = 0; gy <= ARENA_H; gy++) {
    c.beginPath(); c.moveTo(0, gy * TILE); c.lineTo(CANVAS_W, gy * TILE); c.stroke();
  }

  // River
  const ry = RIVER_TOP * TILE, rh = (RIVER_BOT - RIVER_TOP) * TILE;
  c.fillStyle = '#3f74d8';
  c.fillRect(0, ry, CANVAS_W, rh);
  c.strokeStyle = 'rgba(255,255,255,0.25)';
  c.lineWidth = 2;
  for (let i = 0; i < 3; i++) {
    const wy = ry + rh * (i + 1) / 4;
    c.beginPath();
    for (let x = 0; x <= CANVAS_W; x += 12) {
      c.lineTo(x, wy + Math.sin(x / 22 + i * 2) * 3);
    }
    c.stroke();
  }
  // Banks
  c.fillStyle = '#5d4037';
  c.fillRect(0, ry - 6, CANVAS_W, 6);
  c.fillRect(0, ry + rh, CANVAS_W, 6);

  // Bridges
  for (const bx of BRIDGES) {
    const x = (bx - BRIDGE_HALF_W) * TILE, w = BRIDGE_HALF_W * 2 * TILE;
    c.fillStyle = '#8d6e63';
    c.fillRect(x, ry - 6, w, rh + 12);
    c.strokeStyle = '#6d4c41';
    c.lineWidth = 2;
    for (let px = x + 6; px < x + w; px += 10) {
      c.beginPath(); c.moveTo(px, ry - 6); c.lineTo(px, ry + rh + 6); c.stroke();
    }
  }

  // Tower pads
  const pads = [
    [BRIDGES[0], 6.5], [BRIDGES[1], 6.5], [ARENA_W / 2, 3],
    [BRIDGES[0], 25.5], [BRIDGES[1], 25.5], [ARENA_W / 2, 29],
  ];
  c.fillStyle = 'rgba(0,0,0,0.12)';
  for (const [px, py] of pads) {
    c.beginPath();
    c.arc(px * TILE, py * TILE, (py < 10 || py > 22 ? 1.55 : 1.25) * TILE, 0, Math.PI * 2);
    c.fill();
  }

  // Outer wall
  c.strokeStyle = '#4e342e';
  c.lineWidth = 10;
  c.strokeRect(5, 5, CANVAS_W - 10, CANVAS_H - 10);
}

/* ===== Per-frame rendering ===== */
function render() {
  const ctx = cv.getContext('2d');
  ctx.clearRect(0, 0, CANVAS_W, CANVAS_H);
  ctx.drawImage(terrainCv, 0, 0);

  // Deploy-zone hint while a card is selected
  if (gameState === 'playing' && selectedIdx != null) {
    const def = CARDS[player.hand[selectedIdx]];
    if (!def.spell) {
      ctx.fillStyle = 'rgba(100,170,255,0.12)';
      ctx.fillRect(0, RIVER_BOT * TILE, CANVAS_W, (ARENA_H - RIVER_BOT) * TILE);
      // Highlight enemy lanes unlocked by destroyed princess towers
      ctx.fillStyle = 'rgba(126,255,156,0.14)';
      if (unlockedLanes.blue.left) {
        ctx.fillRect(0, (PRINCESS_Y_RED - 1) * TILE, CANVAS_W / 2, (RIVER_TOP - PRINCESS_Y_RED + 1) * TILE);
      }
      if (unlockedLanes.blue.right) {
        ctx.fillRect(CANVAS_W / 2, (PRINCESS_Y_RED - 1) * TILE, CANVAS_W / 2, (RIVER_TOP - PRINCESS_Y_RED + 1) * TILE);
      }
      ctx.setLineDash([8, 6]);
      ctx.strokeStyle = 'rgba(100,170,255,0.7)';
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(0, RIVER_BOT * TILE); ctx.lineTo(CANVAS_W, RIVER_BOT * TILE);
      ctx.stroke();
      ctx.setLineDash([]);
    } else {
      ctx.fillStyle = 'rgba(255,140,60,0.07)';
      ctx.fillRect(0, 0, CANVAS_W, CANVAS_H);
    }
  }

  // Sandbox: subtle full-arena highlight while a spawn card is picked
  if (gameState === 'playing' && sandbox && sandboxSel) {
    ctx.fillStyle = 'rgba(255,255,255,0.05)';
    ctx.fillRect(0, 0, CANVAS_W, CANVAS_H);
  }

  for (const t of towers) drawTower(ctx, t);

  const sorted = [...units].sort((a, b) => a.y - b.y);
  for (const u of sorted) { if (!u.carriedBy) drawUnit(ctx, u); }

  for (const p of projectiles) drawProjectile(ctx, p);
  for (const e of effects) drawEffect(ctx, e);

  // Tsunami wave front
  for (const w of tsunamiWaves) {
    const wy = w.y * TILE;
    const waveH = w.r * TILE;
    ctx.fillStyle = `rgba(79,195,247,${0.35 * (1 - w.t / 3)})`;
    ctx.fillRect(0, wy - waveH / 2, CANVAS_W, waveH);
    // Wave crest
    ctx.strokeStyle = `rgba(255,255,255,${0.6 * (1 - w.t / 3)})`;
    ctx.lineWidth = 3;
    ctx.beginPath();
    for (let x = 0; x <= CANVAS_W; x += 8) {
      const sy = wy + Math.sin(x / 30 + w.t * 8) * 8;
      x === 0 ? ctx.moveTo(x, sy) : ctx.lineTo(x, sy);
    }
    ctx.stroke();
  }

  // Snowman melt puddles
  for (const p of puddles) {
    const ppx = p.x * TILE, ppy = p.y * TILE, pr = p.r * TILE;
    const alpha = 0.3 * (1 - p.t / p.dur);
    ctx.fillStyle = `rgba(179,229,252,${alpha})`;
    ctx.beginPath();
    ctx.ellipse(ppx, ppy, pr, pr * 0.45, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.strokeStyle = `rgba(79,195,247,${alpha * 1.5})`;
    ctx.lineWidth = 1.5;
    ctx.stroke();
  }

  // Slop Master overlays: speech bubble + the victim he's hauling
  for (const u of units) {
    if (u.dead || !u.def.slop) continue;
    if (u.slopState === 'carry' && u.slopTarget && !u.slopTarget.dead) drawCarried(ctx, u);
    if (u.slopState === 'channel' || u.slopState === 'carry') drawSlopBubble(ctx, u);
  }

  const ghostActive = gameState === 'playing' && hover &&
    (sandbox ? !!sandboxSel : selectedIdx != null);
  if (ghostActive) drawGhost(ctx);

  if (gameState === 'playing' && paused) {
    ctx.fillStyle = 'rgba(10,14,30,0.55)';
    ctx.fillRect(0, 0, CANVAS_W, CANVAS_H);
    ctx.font = 'italic 900 40px sans-serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.lineWidth = 6;
    ctx.strokeStyle = 'rgba(0,0,0,0.7)';
    ctx.strokeText('PAUSED', CANVAS_W / 2, CANVAS_H / 2);
    ctx.fillStyle = '#ffc94d';
    ctx.fillText('PAUSED', CANVAS_W / 2, CANVAS_H / 2);
  }
}

function drawHpBar(ctx, x, y, w, frac, color) {
  const h = 5;
  ctx.fillStyle = 'rgba(0,0,0,0.65)';
  ctx.fillRect(x - w / 2 - 1, y - 1, w + 2, h + 2);
  ctx.fillStyle = color;
  ctx.fillRect(x - w / 2, y, w * clamp(frac, 0, 1), h);
}

function drawTower(ctx, t) {
  const s = (t.kind === 'king' ? 2.1 : 1.6) * TILE;
  const px = t.x * TILE, py = t.y * TILE;

  ctx.save();
  ctx.translate(px, py);

  if (t.dead) {
    ctx.globalAlpha = 0.45;
    ctx.fillStyle = '#555';
    roundRectPath(ctx, -s / 2, -s / 2, s, s, 6);
    ctx.fill();
    ctx.strokeStyle = '#333';
    ctx.lineWidth = 3;
    ctx.beginPath();
    ctx.moveTo(-s / 3, -s / 4); ctx.lineTo(s / 4, s / 3);
    ctx.moveTo(s / 3, -s / 3); ctx.lineTo(-s / 5, s / 5);
    ctx.stroke();
    ctx.restore();
    return;
  }

  // Body
  ctx.fillStyle = '#b9c2cc';
  roundRectPath(ctx, -s / 2, -s / 2, s, s, 6);
  ctx.fill();
  ctx.strokeStyle = '#7d8794';
  ctx.lineWidth = 2;
  ctx.stroke();

  // Team roof band
  ctx.fillStyle = teamFill(t.team);
  ctx.fillRect(-s / 2, -s / 2, s, s * 0.26);

  // Battlements
  ctx.fillStyle = '#d7dee6';
  const bw = s / 6;
  for (let i = 0; i < 3; i++) ctx.fillRect(-s / 2 + i * bw * 2 + bw / 2, -s / 2 - bw / 2, bw, bw / 1.6);

  // King crown / princess flag
  ctx.font = `${Math.round(s * 0.34)}px serif`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  if (t.kind === 'king') {
    ctx.fillText('👑', 0, s * 0.14);
    if (!t.active) {
      ctx.fillStyle = 'rgba(0,0,20,0.35)';
      roundRectPath(ctx, -s / 2, -s / 2, s, s, 6);
      ctx.fill();
    }
  } else {
    ctx.fillStyle = teamFill(t.team);
    ctx.beginPath();
    ctx.moveTo(bw, s * 0.05);
    ctx.lineTo(bw, -s * 0.28);
    ctx.lineTo(bw * 2.6, -s * 0.11);
    ctx.closePath();
    ctx.fill();
    ctx.strokeStyle = '#5a3b1e';
    ctx.lineWidth = 2;
    ctx.beginPath(); ctx.moveTo(bw, -s * 0.32); ctx.lineTo(bw, s * 0.35); ctx.stroke();
  }

  // Hit flash
  if (t.flash > 0) {
    ctx.fillStyle = `rgba(255,255,255,${Math.min(1, t.flash * 5) * 0.6})`;
    roundRectPath(ctx, -s / 2, -s / 2, s, s, 6);
    ctx.fill();
  }
  ctx.restore();

  drawHpBar(ctx, px, py - s / 2 - 12, s * 0.9, t.hp / t.maxHp, teamColor(t.team));
}

function drawUnit(ctx, u) {
  let px = u.x * TILE, py = u.y * TILE;
  const r = u.radius * TILE;

  // Bandit dash visuals: vibrate during wind-up, lift off during the dash
  if (u.def.dash) {
    if (u.dashState === 'windup') {
      px += Math.sin(performance.now() / 22) * 2.5;
      py += Math.cos(performance.now() / 31) * 1.5;
    } else if (u.dashState === 'dash') {
      py -= 4;
    }
  }

  // Spring Fack mid-hop arc: parabolic lift over the interpolated path
  if (u.def.springFack && u.hopT > 0) {
    const f = 1 - u.hopT / u.hopDur;
    py -= Math.sin(f * Math.PI) * 12;
  }

  // Stone statue: gray cracked appearance, skip normal rendering
  if (u.stone) {
    const crumble = u.hp / u.maxHp; // visual cracks as HP drops
    ctx.fillStyle = '#78909c';
    ctx.strokeStyle = '#455a64';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.arc(px, py, r, 0, Math.PI * 2);
    ctx.fill();
    ctx.stroke();
    // Cracks
    if (crumble < 0.8) {
      ctx.strokeStyle = '#37474f';
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      ctx.moveTo(px - r * 0.3, py - r * 0.5);
      ctx.lineTo(px + r * 0.2, py + r * 0.1);
      ctx.lineTo(px - r * 0.1, py + r * 0.6);
      ctx.stroke();
    }
    if (crumble < 0.5) {
      ctx.beginPath();
      ctx.moveTo(px + r * 0.4, py - r * 0.3);
      ctx.lineTo(px - r * 0.2, py + r * 0.3);
      ctx.stroke();
    }
    // Stone glyph
    ctx.font = `${Math.max(9, Math.round(r * 1.15))}px serif`;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText('🗿', px, py + 1);
    drawHpBar(ctx, px, py - r - 9, Math.max(18, r * 2.2), u.hp / u.maxHp, '#90a4ae');
    return;
  }

  // Half Tower: brick building appearance
  if (u.def.halfTower) {
    const s = r * 2.8;
    ctx.fillStyle = '#b9c2cc';
    ctx.strokeStyle = '#7d8794';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.arc(px, py, r, 0, Math.PI * 2);
    ctx.fill();
    ctx.stroke();
    // Brick pattern
    ctx.fillStyle = teamFill(u.team);
    ctx.fillRect(px - r, py - r * 0.3, r * 2, r * 0.6);
    ctx.font = `${Math.max(9, Math.round(r * 1.15))}px serif`;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(u.def.glyph, px, py + 1);
    // Show HP
    drawHpBar(ctx, px, py - r - 9, Math.max(18, r * 2.2), u.hp / u.maxHp, teamColor(u.team));
    return;
  }

  // Snowman: melting — radius shrinks as HP drains
  if (u.def.snowman) {
    const meltFrac = clamp(u.hp / u.maxHp, 0, 1);
    const mr = r * (0.3 + meltFrac * 0.7);
    // Shadow
    ctx.fillStyle = 'rgba(0,0,0,0.25)';
    ctx.beginPath();
    ctx.ellipse(px, py + mr * 0.65, mr * 0.9, mr * 0.42, 0, 0, Math.PI * 2);
    ctx.fill();
    // Body (white)
    ctx.fillStyle = '#eceff1';
    ctx.strokeStyle = '#90a4ae';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.arc(px, py, mr, 0, Math.PI * 2);
    ctx.fill();
    ctx.stroke();
    // Head (smaller circle on top)
    if (meltFrac > 0.4) {
      ctx.beginPath();
      ctx.arc(px, py - mr * 0.9, mr * 0.55, 0, Math.PI * 2);
      ctx.fill();
      ctx.stroke();
      // Eyes
      ctx.fillStyle = '#263238';
      ctx.beginPath();
      ctx.arc(px - mr * 0.2, py - mr * 0.95, 1.5, 0, Math.PI * 2);
      ctx.arc(px + mr * 0.2, py - mr * 0.95, 1.5, 0, Math.PI * 2);
      ctx.fill();
      // Carrot nose
      ctx.fillStyle = '#ff9800';
      ctx.beginPath();
      ctx.moveTo(px, py - mr * 0.85);
      ctx.lineTo(px + mr * 0.5, py - mr * 0.82);
      ctx.lineTo(px, py - mr * 0.78);
      ctx.fill();
    }
    drawHpBar(ctx, px, py - r - 14, Math.max(18, r * 2.2), u.hp / u.maxHp, '#b3e5fc');
    return;
  }

  // Spring Fack: bouncing hop animation when attacking
  if (u.def.springFack && u.sfState === 'attacking') {
    const bounce = Math.sin(performance.now() / 120) * 4;
    ctx.fillStyle = 'rgba(0,0,0,0.25)';
    ctx.beginPath();
    ctx.ellipse(px, py + r * 0.65, r * 0.9, r * 0.42, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = '#8bc34a';
    ctx.strokeStyle = '#33691e';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.arc(px, py + bounce, r, 0, Math.PI * 2);
    ctx.fill();
    ctx.stroke();
    ctx.font = `${Math.max(9, Math.round(r * 1.15))}px serif`;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(u.def.glyph, px, py + bounce + 1);
    // Hop counter
    ctx.fillStyle = '#fff';
    ctx.font = 'bold 10px sans-serif';
    ctx.fillText(`${u.sfHops}/${u.def.maxHops}`, px, py + r + 12 + bounce);
    drawHpBar(ctx, px, py - r - 9 + bounce, Math.max(18, r * 2.2), u.hp / u.maxHp, teamColor(u.team));
    return;
  }

  // Bomb tray on ground: burger emoji
  if (u.def.bombTray && u.trayState === 'ground') {
    ctx.fillStyle = 'rgba(0,0,0,0.25)';
    ctx.beginPath();
    ctx.ellipse(px, py + r * 0.65, r * 0.9, r * 0.42, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.font = `${Math.max(14, Math.round(r * 2))}px serif`;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText('🍔', px, py);
    const frac = clamp(u.trayTimer / u.def.trayTimer, 0, 1);
    drawHpBar(ctx, px, py - r - 9, Math.max(18, r * 2.2), frac, '#ff9800');
    return;
  }
  // Bomb tray being carried: draw as small burger icon on carrier instead
  if (u.def.bombTray && (u.trayState === 'carried' || u.trayState === 'stunned')) {
    return;  // skip — drawn as indicator on the carrier
  }

  // Flying unit: elevated shadow + lift
  if (u.flying) {
    ctx.fillStyle = 'rgba(0,0,0,0.2)';
    ctx.beginPath();
    ctx.ellipse(px, py + r * 1.2, r * 1.3, r * 0.5, 0, 0, Math.PI * 2);
    ctx.fill();
    py -= 10;
  }

  // Shadow
  ctx.fillStyle = 'rgba(0,0,0,0.25)';
  ctx.beginPath();
  ctx.ellipse(px, py + r * 0.65, r * 0.9, r * 0.42, 0, 0, Math.PI * 2);
  ctx.fill();

  // Pixel-art sprite if loaded, otherwise circle + emoji fallback
  const slug = spriteSlug(u.def.name);
  const img = SPRITE_CACHE[`${slug}_${u.team}`];
  if (img && img.complete && img.naturalWidth > 0) {
    const h = r * 3.4;
    const w = h * (img.naturalWidth / img.naturalHeight);
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(img, px - w / 2, py - h * 0.72, w, h);
    ctx.imageSmoothingEnabled = true;
  } else {
    // Body
    ctx.fillStyle = teamFill(u.team);
    ctx.strokeStyle = 'rgba(15,15,30,0.85)';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.arc(px, py, r, 0, Math.PI * 2);
    ctx.fill();
    ctx.stroke();
    // Glyph
    ctx.font = `${Math.max(9, Math.round(r * 1.15))}px serif`;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(u.def.glyph, px, py + 1);
  }

  // Hit flash
  if (u.flash > 0) {
    ctx.fillStyle = `rgba(255,255,255,${Math.min(1, u.flash * 6) * 0.7})`;
    ctx.beginPath();
    ctx.arc(px, py, r, 0, Math.PI * 2);
    ctx.fill();
  }

  // Blessed halo
  if (u.isBlessed && u.isBlessed()) {
    ctx.strokeStyle = '#ffc94d';
    ctx.lineWidth = 2.5;
    ctx.beginPath();
    ctx.ellipse(px, py - r * 2.4, r * 0.75, r * 0.28, 0, 0, Math.PI * 2);
    ctx.stroke();
  }
  // Cripple indicator
  if (u.isCrippled && u.isCrippled()) {
    ctx.fillStyle = '#4fc3f7';
    ctx.font = 'bold 11px sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('❄️', px + r + 4, py - r - 3);
  }
  // Insanity marker
  if (u.insane) {
    ctx.fillStyle = '#ff69b4';
    ctx.font = 'bold 13px sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('!', px + r + 3, py - r - 5);
  }
  // Spy disguise indicator
  if (u.def.spy && u.spyDisguised) {
    ctx.fillStyle = 'rgba(0,0,0,0.5)';
    ctx.font = 'bold 14px sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('?', px + r + 3, py - r - 5);
  }
  // Spy revealed indicator
  if (u.def.spy && !u.spyDisguised && u.spyRevealTimer > 0) {
    ctx.fillStyle = '#ff5722';
    ctx.font = 'bold 11px sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('👁', px + r + 4, py - r - 3);
  }
  // Bomb tray carrier indicator: small burger above the unit's head
  if (u.bombTrayRef) {
    ctx.font = `${Math.max(10, Math.round(r * 1.2))}px serif`;
    ctx.textAlign = 'center';
    ctx.fillText('🍔', px, py - r - 14);
  }
  // Witch spawn timer indicator
  if (u.def.witch) {
    const wFrac = clamp(1 - u.witchSpawnTimer / u.def.spawnInterval, 0, 1);
    ctx.fillStyle = '#ce93d8';
    ctx.font = 'bold 9px sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText(`骨骼 ${Math.ceil(u.witchSpawnTimer)}s`, px, py + r + 12);
  }

  drawHpBar(ctx, px, py - r - 9, Math.max(18, r * 2.2), u.hp / u.maxHp, teamColor(u.team));
}

/* Victim being hauled to the river by a Slop Master */
function drawCarried(ctx, sm) {
  const t = sm.slopTarget;
  const bob = Math.sin(performance.now() / 90) * 2;
  const px = sm.x * TILE, py = sm.y * TILE - 34 + bob;
  if (t.isTower) {
    ctx.fillStyle = '#8d6e63';
    ctx.strokeStyle = '#5d4037';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.rect(px - 12, py - 12, 24, 24);
    ctx.fill();
    ctx.stroke();
    ctx.fillStyle = teamFill(t.team);
    ctx.fillRect(px - 12, py - 12, 24, 7);
  } else {
    const slug = spriteSlug(t.def.name);
    const img = SPRITE_CACHE[`${slug}_${t.team}`];
    ctx.imageSmoothingEnabled = false;
    if (img && img.complete && img.naturalWidth > 0) {
      const h = 30, w = h * img.naturalWidth / img.naturalHeight;
      ctx.drawImage(img, px - w / 2, py - h / 2, w, h);
    } else {
      ctx.font = '20px serif';
      ctx.textAlign = 'center';
      ctx.fillText(t.def.glyph, px, py + 7);
    }
    ctx.imageSmoothingEnabled = true;
  }
}

/* Slop Master speech bubble with channel progress bar */
function drawSlopBubble(ctx, sm) {
  const px = sm.x * TILE, py = sm.y * TILE;
  const bw = 56, bh = 20;
  const bx = px - bw / 2, by = py - 58;
  ctx.fillStyle = 'rgba(245,245,250,0.95)';
  roundRectPath(ctx, bx, by, bw, bh, 6);
  ctx.fill();
  ctx.strokeStyle = '#333';
  ctx.lineWidth = 1.5;
  roundRectPath(ctx, bx, by, bw, bh, 6);
  ctx.stroke();
  // Tail
  ctx.beginPath();
  ctx.moveTo(px - 5, by + bh);
  ctx.lineTo(px, by + bh + 7);
  ctx.lineTo(px + 5, by + bh);
  ctx.closePath();
  ctx.fill();

  if (sm.slopState === 'channel') {
    const frac = clamp(sm.slopProgress / sm.channelTotal, 0, 1);
    ctx.fillStyle = '#ddd';
    ctx.fillRect(bx + 5, by + 6, bw - 10, bh - 12);
    ctx.fillStyle = '#43a047';
    ctx.fillRect(bx + 5, by + 6, (bw - 10) * frac, bh - 12);
  } else {
    ctx.fillStyle = '#d32f2f';
    ctx.font = '900 12px sans-serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(sm.slopSay > gameClock ? 'SLOP!' : '…', px, by + bh / 2 + 1);
  }
}

function drawProjectile(ctx, p) {
  if (p.additive) ctx.globalCompositeOperation = 'lighter';
  let px = p.x * TILE, py = p.y * TILE, r = p.size * TILE;
  // Arc: draw shadow on ground, then offset projectile upward
  if (p.arcHeight > 0) {
    const sinT = Math.sin(p.arcProgress * Math.PI);
    const arcPx = p.arcHeight * TILE * sinT;
    // Ground shadow
    ctx.globalAlpha = 0.25;
    ctx.fillStyle = '#000';
    ctx.beginPath();
    ctx.ellipse(px, py + 2, r * 0.7, r * 0.25, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.globalAlpha = 1;
    // Offset projectile up
    py -= arcPx;
    r *= 1 + 0.35 * sinT;  // bigger at peak, smaller near ground
  }
  // Motion trail — for arc projectiles, follow the visual arc tangent
  const dx = p.lx - p.x, dy = p.ly - p.y;
  const d = Math.hypot(dx, dy);
  if (d > 1e-4) {
    let ux = dx / d, uy = dy / d;
    if (p.arcHeight > 0 && p.totalDist > 0) {
      // Tangent = ground direction + arc derivative
      const arcDeriv = -p.arcHeight * Math.PI * Math.cos(p.arcProgress * Math.PI) / p.totalDist;
      const tLen = Math.hypot(ux, uy + arcDeriv) || 1;
      ux /= tLen;
      uy = (uy + arcDeriv) / tLen;
    }
    const tail = r * 3.2;
    const trailCol = p.trailColor || p.color;
    const grad = ctx.createLinearGradient(px, py, px - ux * tail, py - uy * tail);
    grad.addColorStop(0, trailCol);
    grad.addColorStop(1, 'rgba(255,255,255,0)');
    ctx.strokeStyle = grad;
    ctx.lineWidth = r * 1.4;
    ctx.lineCap = 'round';
    ctx.globalAlpha = 0.55;
    ctx.beginPath();
    ctx.moveTo(px, py);
    ctx.lineTo(px - ux * tail, py - uy * tail);
    ctx.stroke();
    ctx.globalAlpha = 1;
  }
  ctx.fillStyle = p.color;
  ctx.shadowColor = p.color;
  ctx.shadowBlur = 8;
  if (p.additive) ctx.globalAlpha = 0.45;
  ctx.beginPath();
  ctx.arc(px, py, r, 0, Math.PI * 2);
  ctx.fill();
  ctx.shadowBlur = 0;
  if (p.additive) ctx.globalAlpha = 1;
  if (p.additive) ctx.globalCompositeOperation = 'source-over';
}

function drawEffect(ctx, e) {
  const k = e.t / e.dur;
  if (e.type === 'ring') {
    const radius = e.r * TILE * (0.3 + k * 0.7);
    // Optional filled circle (e.g. green spell area)
    if (e.fill) {
      ctx.globalAlpha = (e.fillAlpha || 0.3) * (1 - k);
      ctx.fillStyle = e.fill;
      ctx.beginPath();
      ctx.arc(e.x * TILE, e.y * TILE, radius, 0, Math.PI * 2);
      ctx.fill();
    }
    ctx.globalAlpha = 1 - k;
    ctx.strokeStyle = e.color;
    ctx.lineWidth = 3;
    ctx.beginPath();
    ctx.arc(e.x * TILE, e.y * TILE, radius, 0, Math.PI * 2);
    ctx.stroke();
    ctx.globalAlpha = 1;
  } else if (e.type === 'text') {
    ctx.globalAlpha = 1 - k;
    ctx.fillStyle = e.color;
    ctx.font = 'bold 13px sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText(e.text, e.x * TILE, e.y * TILE - k * 22);
    ctx.globalAlpha = 1;
  } else if (e.type === 'banner') {
    const scale = 1 + 0.25 * Math.sin(Math.min(1, k) * Math.PI);
    ctx.save();
    ctx.translate(CANVAS_W / 2, CANVAS_H * 0.38);
    ctx.scale(scale, scale);
    ctx.globalAlpha = k > 0.75 ? (1 - k) / 0.25 : 1;
    ctx.font = 'italic 900 34px sans-serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.lineWidth = 6;
    ctx.strokeStyle = 'rgba(0,0,0,0.7)';
    ctx.strokeText(e.text, 0, 0);
    ctx.fillStyle = '#ffc94d';
    ctx.fillText(e.text, 0, 0);
    ctx.restore();
    ctx.globalAlpha = 1;
  }
}

function drawGhost(ctx) {
  const def = sandbox ? CARDS[sandboxSel] : CARDS[player.hand[selectedIdx]];
  const ok = sandbox ? true : placementValid(def, hover.x, hover.y, TEAM_BLUE);
  const col = ok ? (sandbox ? teamColor(sandboxTeam) : def.spell ? '#ffb74d' : '#7fd4ff') : '#ff5252';

  ctx.globalAlpha = 0.55;
  if (def.spell) {
    ctx.strokeStyle = col;
    ctx.lineWidth = 2.5;
    ctx.beginPath();
    ctx.arc(hover.x * TILE, hover.y * TILE, def.radius * TILE, 0, Math.PI * 2);
    ctx.stroke();
    ctx.fillStyle = col;
    ctx.globalAlpha = 0.18;
    ctx.fill();
  } else {
    const offs = spawnOffsets(def.count);
    ctx.fillStyle = col;
    ctx.strokeStyle = col;
    for (const [ox, oy] of offs) {
      const gx = clamp(hover.x + ox, 0.4, ARENA_W - 0.4) * TILE;
      const gy = clamp(hover.y + oy, 0.4, ARENA_H - 0.4) * TILE;
      ctx.globalAlpha = 0.25;
      ctx.beginPath();
      ctx.arc(gx, gy, def.radius * TILE, 0, Math.PI * 2);
      ctx.fill();
      ctx.globalAlpha = 0.8;
      ctx.stroke();
    }
  }
  ctx.globalAlpha = 1;

  if (!ok) {
    ctx.fillStyle = '#ff5252';
    ctx.font = 'bold 16px sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('✕', hover.x * TILE, hover.y * TILE + 5);
  }
}

function roundRectPath(ctx, x, y, w, h, r) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r);
  ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r);
  ctx.arcTo(x, y, x + w, y, r);
  ctx.closePath();
}
